version: '3.8'

services:
  api:
    build:
      context: ./api
    container_name: bierges-api
    ports:
      - "3001:3001"
    networks:
      - app-network

  front:
    build:
      context: ./40bierges
    container_name: bierges-front
    env_file:
      - ./api/.env
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - api

  nginx:
    image: nginx:latest
    container_name: bierges-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - front
      - api
    networks:
      - app-network

networks:
  app-network:
    driver: bridge