version: '3.8'

services:
  api:
    build:
      context: ./api
    container_name: bierges-api
    ports:
      - "3001:3001"
    networks:
      - app-network

  front:
    build:
      context: ./40bierges
    container_name: bierges-front
    env_file:
      - /api/.env
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - api

networks:
  app-network:
    driver: bridge